# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(choices=[('AL', 'Albania'), ('AT', 'Austria'), ('BE', 'Belgium'), ('HR', 'Croatia'), ('CZ', 'Czech'), ('EN', 'England'), ('FR', 'France'), ('DE', 'Germany'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IT', 'Italy'), ('NI', 'Northern Ireland'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RI', 'Republic of Ireland'), ('RO', 'Romania'), ('RU', 'Russia'), ('SK', 'Slovakia'), ('SP', 'Spain'), ('SE', 'Sweden'), ('SW', 'Switzerland'), ('TK', 'Turkey'), ('UK', 'Ukraine'), ('WA', 'Wales')], max_length=2)),
                ('away_team', models.CharField(choices=[('AL', 'Albania'), ('AT', 'Austria'), ('BE', 'Belgium'), ('HR', 'Croatia'), ('CZ', 'Czech'), ('EN', 'England'), ('FR', 'France'), ('DE', 'Germany'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IT', 'Italy'), ('NI', 'Northern Ireland'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RI', 'Republic of Ireland'), ('RO', 'Romania'), ('RU', 'Russia'), ('SK', 'Slovakia'), ('SP', 'Spain'), ('SE', 'Sweden'), ('SW', 'Switzerland'), ('TK', 'Turkey'), ('UK', 'Ukraine'), ('WA', 'Wales')], max_length=2)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
            ],
        ),
    ]
