# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(choices=[('AL', 'Albania'), ('AT', 'Austria'), ('BE', 'Belgium'), ('HR', 'Croatia'), ('CZ', 'Czech'), ('EN', 'England'), ('FR', 'France'), ('DE', 'Germany'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IT', 'Italy'), ('NI', 'N. Ireland'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RI', 'R. of Ireland'), ('RO', 'Romania'), ('RU', 'Russia'), ('SK', 'Slovakia'), ('SP', 'Spain'), ('SE', 'Sweden'), ('SW', 'Switzerland'), ('TK', 'Turkey'), ('UK', 'Ukraine'), ('WA', 'Wales')], max_length=2)),
                ('away_team', models.CharField(choices=[('AL', 'Albania'), ('AT', 'Austria'), ('BE', 'Belgium'), ('HR', 'Croatia'), ('CZ', 'Czech'), ('EN', 'England'), ('FR', 'France'), ('DE', 'Germany'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IT', 'Italy'), ('NI', 'N. Ireland'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RI', 'R. of Ireland'), ('RO', 'Romania'), ('RU', 'Russia'), ('SK', 'Slovakia'), ('SP', 'Spain'), ('SE', 'Sweden'), ('SW', 'Switzerland'), ('TK', 'Turkey'), ('UK', 'Ukraine'), ('WA', 'Wales')], max_length=2)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('group', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score_tip', models.IntegerField()),
                ('away_score_tip', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('scoring_field', models.CharField(blank=True, max_length=256)),
                ('is_score_calculated', models.BooleanField(default=False)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
