# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(choices=[('PS', 'Paris Saint-Germain'), ('AR', 'Arsenal'), ('BA', 'Basel'), ('LU', 'Ludogorec Razgrad'), ('BN', 'Benfica'), ('NA', 'Napoli'), ('DK', 'Dinamo Kijev'), ('BS', 'Besiktas'), ('BC', 'Barcelona'), ('MC', 'Manchester City'), ('BM', 'Borussia Monchengladbach'), ('CE', 'Celtic'), ('BY', 'Bayern Munchen'), ('AM', 'Atletico Madrid'), ('PE', 'PSV Eindhoven'), ('RS', 'FK Rosztov'), ('CM', 'CSZKA Moszkva'), ('BL', 'Bayer Leverkusen'), ('TO', 'Tottenham'), ('MO', 'Monaco'), ('RM', 'Real Madrid'), ('BD', 'Borussia Dortmund'), ('SC', 'Sporting CP'), ('LW', 'Legia Warszawa'), ('LC', 'Leicester City'), ('PP', 'Porto'), ('BR', 'FC Bruges'), ('KO', 'Kobenhavn'), ('JU', 'Juventus'), ('SV', 'Sevilla'), ('LY', 'Lyon'), ('DZ', 'Dinamo Zagreb')], max_length=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(choices=[('PS', 'Paris Saint-Germain'), ('AR', 'Arsenal'), ('BA', 'Basel'), ('LU', 'Ludogorec Razgrad'), ('BN', 'Benfica'), ('NA', 'Napoli'), ('DK', 'Dinamo Kijev'), ('BS', 'Besiktas'), ('BC', 'Barcelona'), ('MC', 'Manchester City'), ('BM', 'Borussia Monchengladbach'), ('CE', 'Celtic'), ('BY', 'Bayern Munchen'), ('AM', 'Atletico Madrid'), ('PE', 'PSV Eindhoven'), ('RS', 'FK Rosztov'), ('CM', 'CSZKA Moszkva'), ('BL', 'Bayer Leverkusen'), ('TO', 'Tottenham'), ('MO', 'Monaco'), ('RM', 'Real Madrid'), ('BD', 'Borussia Dortmund'), ('SC', 'Sporting CP'), ('LW', 'Legia Warszawa'), ('LC', 'Leicester City'), ('PP', 'Porto'), ('BR', 'FC Bruges'), ('KO', 'Kobenhavn'), ('JU', 'Juventus'), ('SV', 'Sevilla'), ('LY', 'Lyon'), ('DZ', 'Dinamo Zagreb')], max_length=2),
        ),
    ]
