# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_tip_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
        ),
    ]
