# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20160507_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
