# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_tip_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='scoring_field',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
