# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_tip_scoring_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='is_score_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
