# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=30)),
                ('max_size', models.IntegerField()),
                ('points_for_exact_guess', models.IntegerField()),
                ('points_for_goal_difference', models.IntegerField()),
                ('points_for_outcome', models.IntegerField()),
                ('points_for_number_of_goals', models.IntegerField()),
                ('points_for_exact_home_goals', models.IntegerField()),
                ('points_for_exact_away_goals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeagueParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
